apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: regseek-com-tls
spec:
  secretName: regseek-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: regseek.com
  dnsNames:
    - regseek.com
    - www.regseek.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - regseek.com
          - www.regseek.com